// Lianliankan.idl : Lianliankan.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(Lianliankan.tlb)。

#include "olectl.h"
[ uuid(834E1909-6896-40ED-B353-8ECFBE6B3EA8), version(1.0) ]
library Lianliankan
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CLianliankanDoc 的主调度接口
	
	[ uuid(2FFE508F-46E5-49AC-AFCE-245C24812F75) ]
	dispinterface ILianliankan
	{
		properties:
			
		methods:
	};

	//  CLianliankanDoc 的类信息
	
	[ uuid(BDC3A4DA-E97E-49F0-9184-F8A386CFBF52) ]
	coclass Lianliankan
	{
		[default] dispinterface ILianliankan;
	};
	//  GameDlg 的主调度接口
		
	[ uuid(F497B997-B536-44C5-830B-FD433615F5F0) ]
	dispinterface IGameDlg
	{
		properties:
		methods:
	};

	//  GameDlg 的类信息

	[ uuid(1F415D0B-FF70-4F55-9BB4-AB01C937C653) ]
	coclass GameDlg
	{
		[default] dispinterface IGameDlg;
	};
	//  GameHelp 的主调度接口
		
	[ uuid(8D810658-D053-4FF9-AA10-AE6AEE92AC9F) ]
	dispinterface IGameHelp
	{
		properties:
		methods:
	};

	//  GameHelp 的类信息

	[ uuid(6FF39C53-C6BB-4CB9-800B-1E6DE387FF20) ]
	coclass GameHelp
	{
		[default] dispinterface IGameHelp;
	};
};
